// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.3.4
// Project name: Jarvis

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
lv_obj_t *ui_jarvisScreen;
lv_obj_t *ui_dateArc;
lv_obj_t *ui_monthLabel;
lv_obj_t *ui_dayLabel;
lv_obj_t *ui_timeLabel;
lv_obj_t *ui_tempArc;
lv_obj_t *ui_tempValue;
lv_obj_t *ui_tempHigh;
lv_obj_t *ui_tempLow;
lv_obj_t *ui_weatherIcon;
lv_obj_t *ui_cityLabel;
lv_obj_t *ui_notificationPanel;
void ui_event_brightnessSlider( lv_event_t * e);
lv_obj_t *ui_brightnessSlider;
lv_obj_t *ui_brightnessValue;
lv_obj_t *ui_brightnessImage;
lv_obj_t *ui_weekdayLabel;
lv_obj_t *ui_notifLabel;
lv_obj_t *ui_connectPanel;
lv_obj_t *ui_connectPanel1;
lv_obj_t *ui_logPanel;
lv_obj_t *ui_logLabel;
lv_obj_t *ui_cameraPanel;
lv_obj_t *ui_cameraTitle;
void ui_event_cameraCapture( lv_event_t * e);
lv_obj_t *ui_cameraCapture;
lv_obj_t *ui_cameraText;
lv_obj_t *ui_findTimer;
void ui_event_findPhone( lv_event_t * e);
lv_obj_t *ui_findPhone;
lv_obj_t *ui_musicPanel;
void ui_event_musicPrevious( lv_event_t * e);
lv_obj_t *ui_musicPrevious;
void ui_event_musicNext( lv_event_t * e);
lv_obj_t *ui_musicNext;
void ui_event_musicPlay( lv_event_t * e);
lv_obj_t *ui_musicPlay;
lv_obj_t *ui_musicTitle;
lv_obj_t *ui_alertPanel;
lv_obj_t *ui_alertTitle;
lv_obj_t *ui_alertText;
lv_obj_t *ui_alertTime;
void ui_event_alertPrev( lv_event_t * e);
lv_obj_t *ui_alertPrev;
void ui_event_alertNext( lv_event_t * e);
lv_obj_t *ui_alertNext;
void ui_event_alertClose( lv_event_t * e);
lv_obj_t *ui_alertClose;
lv_obj_t *ui____initial_actions0;
const lv_img_dsc_t *ui_imgset_btn_bg_[3] = {&ui_img_btn_bg_1_png, &ui_img_btn_bg_2_png, &ui_img_btn_bg_3_png};
const lv_img_dsc_t *ui_imgset_call[2] = {&ui_img_call1_png, &ui_img_call2_png};
const lv_img_dsc_t *ui_imgset_dy[8] = {&ui_img_dy0_png, &ui_img_dy1_png, &ui_img_dy2_png, &ui_img_dy3_png, &ui_img_dy4_png, &ui_img_dy5_png, &ui_img_dy6_png, &ui_img_dy7_png};
const lv_img_dsc_t *ui_imgset_heart[1] = {&ui_img_heart2_png};
const lv_img_dsc_t *ui_imgset_nt[8] = {&ui_img_nt0_png, &ui_img_nt1_png, &ui_img_nt2_png, &ui_img_nt3_png, &ui_img_nt4_png, &ui_img_nt5_png, &ui_img_nt6_png, &ui_img_nt7_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_brightnessSlider( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_VALUE_CHANGED) {
      _ui_slider_set_text_value( ui_brightnessValue, target, "", "%");
      brightnessChange( e );
}
}
void ui_event_cameraCapture( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      cameraCapture( e );
}
}
void ui_event_findPhone( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      findPhone( e );
}
}
void ui_event_musicPrevious( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      musicPrevious( e );
}
}
void ui_event_musicNext( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      musicNext( e );
}
}
void ui_event_musicPlay( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      musicToggle( e );
}
}
void ui_event_alertPrev( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      alertPrev( e );
}
}
void ui_event_alertNext( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      alertNext( e );
}
}
void ui_event_alertClose( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_alertPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}

///////////////////// SCREENS ////////////////////
void ui_jarvisScreen_screen_init(void)
{
ui_jarvisScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_jarvisScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_jarvisScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_jarvisScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_jarvisScreen, &ui_img_jarvis_bg_png, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_dateArc = lv_arc_create(ui_jarvisScreen);
lv_obj_set_width( ui_dateArc, 90);
lv_obj_set_height( ui_dateArc, 90);
lv_obj_set_x( ui_dateArc, -303 );
lv_obj_set_y( ui_dateArc, -142 );
lv_obj_set_align( ui_dateArc, LV_ALIGN_CENTER );
lv_arc_set_bg_angles(ui_dateArc,0,360);
lv_obj_set_style_arc_color(ui_dateArc, lv_color_hex(0x01D3D1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_dateArc, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_dateArc, 7, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_dateArc, lv_color_hex(0x01D3D1), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_dateArc, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_dateArc, 7, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_dateArc, false, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_dateArc, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_dateArc, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_monthLabel = lv_label_create(ui_jarvisScreen);
lv_obj_set_width( ui_monthLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_monthLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_monthLabel, 139 );
lv_obj_set_y( ui_monthLabel, -190 );
lv_obj_set_align( ui_monthLabel, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_monthLabel,"January");
lv_obj_set_style_text_color(ui_monthLabel, lv_color_hex(0x01D3D1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_monthLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_monthLabel, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_dayLabel = lv_label_create(ui_jarvisScreen);
lv_obj_set_width( ui_dayLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_dayLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_dayLabel, -305 );
lv_obj_set_y( ui_dayLabel, -143 );
lv_obj_set_align( ui_dayLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_dayLabel,"18");
lv_obj_set_style_text_color(ui_dayLabel, lv_color_hex(0x01D3D1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_dayLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_dayLabel, &lv_font_montserrat_40, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_timeLabel = lv_label_create(ui_jarvisScreen);
lv_obj_set_width( ui_timeLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_timeLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_timeLabel, -131 );
lv_obj_set_y( ui_timeLabel, -152 );
lv_obj_set_align( ui_timeLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_timeLabel,"11:45pm");
lv_obj_set_style_text_color(ui_timeLabel, lv_color_hex(0x01D3D1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_timeLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_timeLabel, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_tempArc = lv_arc_create(ui_jarvisScreen);
lv_obj_set_width( ui_tempArc, 60);
lv_obj_set_height( ui_tempArc, 60);
lv_obj_set_x( ui_tempArc, 142 );
lv_obj_set_y( ui_tempArc, -157 );
lv_obj_set_align( ui_tempArc, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_tempArc, LV_OBJ_FLAG_CLICKABLE );    /// Flags
lv_obj_set_style_arc_color(ui_tempArc, lv_color_hex(0x01D3D1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_tempArc, 150, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_tempArc, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_tempArc, false, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_tempArc, lv_color_hex(0x01D3D1), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_tempArc, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_tempArc, 8, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_tempArc, false, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_tempArc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_tempArc, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_tempValue = lv_label_create(ui_tempArc);
lv_obj_set_width( ui_tempValue, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_tempValue, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_tempValue, LV_ALIGN_CENTER );
lv_label_set_text(ui_tempValue,"0°");
lv_obj_set_style_text_color(ui_tempValue, lv_color_hex(0x01D3D1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_tempValue, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_tempValue, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_tempHigh = lv_label_create(ui_tempArc);
lv_obj_set_width( ui_tempHigh, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_tempHigh, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_tempHigh, -12 );
lv_obj_set_y( ui_tempHigh, 0 );
lv_obj_set_align( ui_tempHigh, LV_ALIGN_BOTTOM_RIGHT );
lv_label_set_text(ui_tempHigh,"0");
lv_obj_set_style_text_color(ui_tempHigh, lv_color_hex(0x01D3D1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_tempHigh, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_tempHigh, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_tempLow = lv_label_create(ui_tempArc);
lv_obj_set_width( ui_tempLow, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_tempLow, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_tempLow, 12 );
lv_obj_set_y( ui_tempLow, 0 );
lv_obj_set_align( ui_tempLow, LV_ALIGN_BOTTOM_LEFT );
lv_label_set_text(ui_tempLow,"0");
lv_obj_set_style_text_color(ui_tempLow, lv_color_hex(0x01D3D1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_tempLow, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_tempLow, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_weatherIcon = lv_img_create(ui_jarvisScreen);
lv_img_set_src(ui_weatherIcon, &ui_img_dy3_png);
lv_obj_set_width( ui_weatherIcon, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_weatherIcon, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_weatherIcon, 71 );
lv_obj_set_y( ui_weatherIcon, -119 );
lv_obj_set_align( ui_weatherIcon, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_weatherIcon, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_weatherIcon, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_weatherIcon,200);
lv_obj_set_style_radius(ui_weatherIcon, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_weatherIcon, lv_color_hex(0x01D3D1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_weatherIcon, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_weatherIcon, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor(ui_weatherIcon, lv_color_hex(0x01D3D1), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_weatherIcon, 240, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_cityLabel = lv_label_create(ui_jarvisScreen);
lv_obj_set_width( ui_cityLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_cityLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_cityLabel, 82 );
lv_obj_set_y( ui_cityLabel, -205 );
lv_obj_set_align( ui_cityLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_cityLabel,"");
lv_obj_set_style_text_color(ui_cityLabel, lv_color_hex(0x01D3D1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_cityLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_notificationPanel = lv_obj_create(ui_jarvisScreen);
lv_obj_set_width( ui_notificationPanel, 96);
lv_obj_set_height( ui_notificationPanel, 143);
lv_obj_set_x( ui_notificationPanel, 315 );
lv_obj_set_y( ui_notificationPanel, -113 );
lv_obj_set_align( ui_notificationPanel, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_notificationPanel,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_notificationPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
lv_obj_set_scrollbar_mode(ui_notificationPanel, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_bg_color(ui_notificationPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_notificationPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_notificationPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_notificationPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_notificationPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_notificationPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_notificationPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_notificationPanel, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_notificationPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_brightnessSlider = lv_slider_create(ui_jarvisScreen);
lv_slider_set_range(ui_brightnessSlider, 1,100);
lv_slider_set_value( ui_brightnessSlider, 95, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_brightnessSlider)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_brightnessSlider, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_brightnessSlider, 125);
lv_obj_set_height( ui_brightnessSlider, 10);
lv_obj_set_x( ui_brightnessSlider, -210 );
lv_obj_set_y( ui_brightnessSlider, 8 );
lv_obj_set_align( ui_brightnessSlider, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_brightnessSlider, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_brightnessSlider, lv_color_hex(0x01D3D1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_brightnessSlider, 100, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_brightnessSlider, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_brightnessSlider, lv_color_hex(0x01D3D1), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_brightnessSlider, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_brightnessSlider, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_brightnessSlider, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_brightnessValue = lv_label_create(ui_jarvisScreen);
lv_obj_set_width( ui_brightnessValue, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_brightnessValue, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_brightnessValue, -235 );
lv_obj_set_y( ui_brightnessValue, -9 );
lv_obj_set_align( ui_brightnessValue, LV_ALIGN_CENTER );
lv_label_set_text(ui_brightnessValue,"95%");
lv_obj_set_style_text_color(ui_brightnessValue, lv_color_hex(0x01D3D1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_brightnessValue, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_brightnessValue, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_brightnessImage = lv_img_create(ui_jarvisScreen);
lv_img_set_src(ui_brightnessImage, &ui_img_brightness_png);
lv_obj_set_width( ui_brightnessImage, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_brightnessImage, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_brightnessImage, -312 );
lv_obj_set_y( ui_brightnessImage, 7 );
lv_obj_set_align( ui_brightnessImage, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_brightnessImage, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_brightnessImage, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_brightnessImage,200);
lv_obj_set_style_img_recolor(ui_brightnessImage, lv_color_hex(0x01D3D1), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_brightnessImage, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_weekdayLabel = lv_label_create(ui_jarvisScreen);
lv_obj_set_width( ui_weekdayLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_weekdayLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_weekdayLabel, -423 );
lv_obj_set_y( ui_weekdayLabel, -190 );
lv_obj_set_align( ui_weekdayLabel, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_weekdayLabel,"Thursday");
lv_obj_set_style_text_color(ui_weekdayLabel, lv_color_hex(0x01D3D1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_weekdayLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_weekdayLabel, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_weekdayLabel, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_notifLabel = lv_label_create(ui_jarvisScreen);
lv_obj_set_width( ui_notifLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_notifLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_notifLabel, 311 );
lv_obj_set_y( ui_notifLabel, -209 );
lv_obj_set_align( ui_notifLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_notifLabel,"Notifications");
lv_obj_set_style_text_color(ui_notifLabel, lv_color_hex(0x01D3D1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_notifLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_notifLabel, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_connectPanel = lv_obj_create(ui_jarvisScreen);
lv_obj_set_width( ui_connectPanel, 90);
lv_obj_set_height( ui_connectPanel, 90);
lv_obj_set_x( ui_connectPanel, 16 );
lv_obj_set_y( ui_connectPanel, -22 );
lv_obj_set_align( ui_connectPanel, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_connectPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_connectPanel, 45, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_connectPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_connectPanel, 200, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_connectPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_connectPanel1 = lv_obj_create(ui_jarvisScreen);
lv_obj_set_width( ui_connectPanel1, 30);
lv_obj_set_height( ui_connectPanel1, 30);
lv_obj_set_x( ui_connectPanel1, -188 );
lv_obj_set_y( ui_connectPanel1, 178 );
lv_obj_set_align( ui_connectPanel1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_connectPanel1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_connectPanel1, 15, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_connectPanel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_connectPanel1, 200, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_connectPanel1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_logPanel = lv_obj_create(ui_jarvisScreen);
lv_obj_set_width( ui_logPanel, 150);
lv_obj_set_height( ui_logPanel, 135);
lv_obj_set_x( ui_logPanel, -36 );
lv_obj_set_y( ui_logPanel, -62 );
lv_obj_set_align( ui_logPanel, LV_ALIGN_BOTTOM_RIGHT );
lv_obj_set_scrollbar_mode(ui_logPanel, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_scroll_dir(ui_logPanel, LV_DIR_VER);
lv_obj_set_style_bg_color(ui_logPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_logPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_logPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_logPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_logPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_logPanel, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_logPanel, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_logLabel = lv_label_create(ui_logPanel);
lv_obj_set_width( ui_logLabel, lv_pct(90));
lv_obj_set_height( ui_logLabel, LV_SIZE_CONTENT);   /// 123
lv_obj_set_align( ui_logLabel, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_logLabel,"Starting device\nInitializing BLE\nReady to connect\nSystem ready\nControl music, remote photo capture, weather information and notifications available after connection with Chronos app");
lv_obj_set_style_text_color(ui_logLabel, lv_color_hex(0x01D3D1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_logLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_logLabel, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_logLabel, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_logLabel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_logLabel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_logLabel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_logLabel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_cameraPanel = lv_obj_create(ui_jarvisScreen);
lv_obj_set_width( ui_cameraPanel, 151);
lv_obj_set_height( ui_cameraPanel, 110);
lv_obj_set_x( ui_cameraPanel, 43 );
lv_obj_set_y( ui_cameraPanel, 176 );
lv_obj_set_align( ui_cameraPanel, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_cameraPanel,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_cameraPanel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_cameraPanel, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_cameraPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_cameraPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_cameraPanel, 230, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_cameraPanel, lv_color_hex(0x01D3D1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_cameraPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_cameraPanel, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_cameraPanel, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_cameraPanel, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_cameraPanel, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_cameraTitle = lv_label_create(ui_cameraPanel);
lv_obj_set_width( ui_cameraTitle, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_cameraTitle, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_cameraTitle, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_cameraTitle,"Camera");
lv_obj_set_style_text_color(ui_cameraTitle, lv_color_hex(0x01D3D1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_cameraTitle, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_cameraTitle, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_cameraCapture = lv_img_create(ui_cameraPanel);
lv_img_set_src(ui_cameraCapture, &ui_img_diaphragm_png);
lv_obj_set_width( ui_cameraCapture, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_cameraCapture, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_cameraCapture, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_cameraCapture, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_cameraCapture, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_cameraCapture, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_cameraCapture, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_cameraCapture, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor(ui_cameraCapture, lv_color_hex(0x01D3D1), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_cameraCapture, 150, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_cameraCapture, 10, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_bg_color(ui_cameraCapture, lv_color_hex(0x01D3D1), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_cameraCapture, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_border_color(ui_cameraCapture, lv_color_hex(0x01D3D1), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_border_opa(ui_cameraCapture, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_border_width(ui_cameraCapture, 3, LV_PART_MAIN| LV_STATE_PRESSED);

ui_cameraText = lv_label_create(ui_cameraPanel);
lv_obj_set_width( ui_cameraText, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_cameraText, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_cameraText, LV_ALIGN_CENTER );
lv_label_set_text(ui_cameraText,"Click to Capture");
lv_obj_set_style_text_color(ui_cameraText, lv_color_hex(0x01D3D1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_cameraText, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_cameraText, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_findTimer = lv_arc_create(ui_jarvisScreen);
lv_obj_set_width( ui_findTimer, 60);
lv_obj_set_height( ui_findTimer, 60);
lv_obj_set_x( ui_findTimer, 170 );
lv_obj_set_y( ui_findTimer, -39 );
lv_obj_set_align( ui_findTimer, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_findTimer, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_findTimer, LV_OBJ_FLAG_CLICKABLE );    /// Flags
lv_arc_set_bg_angles(ui_findTimer,0,360);
lv_obj_set_style_arc_color(ui_findTimer, lv_color_hex(0x01D3D1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_findTimer, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_findTimer, 7, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_findTimer, lv_color_hex(0x01D3D1), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_findTimer, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_findTimer, 7, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_findTimer, false, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_findTimer, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_findTimer, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_findPhone = lv_img_create(ui_findTimer);
lv_img_set_src(ui_findPhone, &ui_img_32_serach_png);
lv_obj_set_width( ui_findPhone, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_findPhone, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_findPhone, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_findPhone, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_findPhone, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_findPhone, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_findPhone, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_findPhone, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor(ui_findPhone, lv_color_hex(0x01D3D1), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_findPhone, 200, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_findPhone, 16, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_bg_color(ui_findPhone, lv_color_hex(0x01D3D1), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_findPhone, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_border_color(ui_findPhone, lv_color_hex(0x01D3D1), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_border_opa(ui_findPhone, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_border_width(ui_findPhone, 3, LV_PART_MAIN| LV_STATE_PRESSED);

ui_musicPanel = lv_obj_create(ui_jarvisScreen);
lv_obj_set_width( ui_musicPanel, 146);
lv_obj_set_height( ui_musicPanel, 69);
lv_obj_set_x( ui_musicPanel, 126 );
lv_obj_set_y( ui_musicPanel, 79 );
lv_obj_set_align( ui_musicPanel, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_musicPanel, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_musicPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_musicPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_musicPanel, 230, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_musicPanel, lv_color_hex(0x01D3D1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_musicPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_musicPanel, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_musicPanel, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_musicPanel, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_musicPanel, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_musicPrevious = lv_img_create(ui_musicPanel);
lv_img_set_src(ui_musicPrevious, &ui_img_back_32m_png);
lv_obj_set_width( ui_musicPrevious, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_musicPrevious, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_musicPrevious, LV_ALIGN_BOTTOM_LEFT );
lv_obj_add_flag( ui_musicPrevious, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_musicPrevious, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_musicPrevious, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_musicPrevious, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_musicPrevious, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor(ui_musicPrevious, lv_color_hex(0x01D3D1), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_musicPrevious, 150, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_musicPrevious, 10, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_bg_color(ui_musicPrevious, lv_color_hex(0x01D3D1), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_musicPrevious, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_border_color(ui_musicPrevious, lv_color_hex(0x01D3D1), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_border_opa(ui_musicPrevious, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_border_width(ui_musicPrevious, 3, LV_PART_MAIN| LV_STATE_PRESSED);

ui_musicNext = lv_img_create(ui_musicPanel);
lv_img_set_src(ui_musicNext, &ui_img_next_32m_png);
lv_obj_set_width( ui_musicNext, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_musicNext, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_musicNext, LV_ALIGN_BOTTOM_RIGHT );
lv_obj_add_flag( ui_musicNext, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_musicNext, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_musicNext, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_musicNext, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_musicNext, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor(ui_musicNext, lv_color_hex(0x01D3D1), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_musicNext, 150, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_musicNext, 10, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_bg_color(ui_musicNext, lv_color_hex(0x01D3D1), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_musicNext, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_border_color(ui_musicNext, lv_color_hex(0x01D3D1), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_border_opa(ui_musicNext, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_border_width(ui_musicNext, 3, LV_PART_MAIN| LV_STATE_PRESSED);

ui_musicPlay = lv_img_create(ui_musicPanel);
lv_img_set_src(ui_musicPlay, &ui_img_32_play_png);
lv_obj_set_width( ui_musicPlay, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_musicPlay, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_musicPlay, LV_ALIGN_BOTTOM_MID );
lv_obj_add_flag( ui_musicPlay, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_musicPlay, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_musicPlay, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_musicPlay, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_musicPlay, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor(ui_musicPlay, lv_color_hex(0x01D3D1), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_musicPlay, 150, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_musicPlay, 10, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_bg_color(ui_musicPlay, lv_color_hex(0x01D3D1), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_musicPlay, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_border_color(ui_musicPlay, lv_color_hex(0x01D3D1), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_border_opa(ui_musicPlay, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_border_width(ui_musicPlay, 3, LV_PART_MAIN| LV_STATE_PRESSED);

ui_musicTitle = lv_label_create(ui_musicPanel);
lv_obj_set_width( ui_musicTitle, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_musicTitle, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_musicTitle, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_musicTitle,"Music Control");
lv_obj_set_style_text_color(ui_musicTitle, lv_color_hex(0x01D3D1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_musicTitle, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_musicTitle, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_alertPanel = lv_obj_create(ui_jarvisScreen);
lv_obj_set_width( ui_alertPanel, 300);
lv_obj_set_height( ui_alertPanel, 282);
lv_obj_set_x( ui_alertPanel, -196 );
lv_obj_set_y( ui_alertPanel, 42 );
lv_obj_set_align( ui_alertPanel, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_alertPanel, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_IGNORE_LAYOUT );   /// Flags
lv_obj_clear_flag( ui_alertPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_alertPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_alertPanel, 235, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_alertPanel, lv_color_hex(0x01D3D1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_alertPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_alertTitle = lv_label_create(ui_alertPanel);
lv_obj_set_width( ui_alertTitle, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_alertTitle, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_alertTitle, 0 );
lv_obj_set_y( ui_alertTitle, -10 );
lv_obj_set_align( ui_alertTitle, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_alertTitle,"Title");
lv_obj_set_style_text_color(ui_alertTitle, lv_color_hex(0x01D3D1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_alertTitle, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_alertTitle, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_alertText = lv_label_create(ui_alertPanel);
lv_obj_set_width( ui_alertText, 250);
lv_obj_set_height( ui_alertText, 187);
lv_obj_set_x( ui_alertText, 0 );
lv_obj_set_y( ui_alertText, 25 );
lv_obj_set_align( ui_alertText, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_alertText,"This is a message received from the connected phone via Chronos app");
lv_obj_set_style_text_color(ui_alertText, lv_color_hex(0x01D3D1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_alertText, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_alertText, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_alertTime = lv_label_create(ui_alertPanel);
lv_obj_set_width( ui_alertTime, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_alertTime, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_alertTime, 0 );
lv_obj_set_y( ui_alertTime, 10 );
lv_obj_set_align( ui_alertTime, LV_ALIGN_BOTTOM_MID );
lv_label_set_text(ui_alertTime,"10:45");
lv_obj_set_style_text_color(ui_alertTime, lv_color_hex(0x01D3D1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_alertTime, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_alertTime, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_alertPrev = lv_img_create(ui_alertPanel);
lv_img_set_src(ui_alertPrev, &ui_img_32_back_png);
lv_obj_set_width( ui_alertPrev, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_alertPrev, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_alertPrev, -15 );
lv_obj_set_y( ui_alertPrev, 15 );
lv_obj_set_align( ui_alertPrev, LV_ALIGN_BOTTOM_LEFT );
lv_obj_add_flag( ui_alertPrev, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_alertPrev, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_alertPrev, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_alertPrev, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_alertPrev, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor(ui_alertPrev, lv_color_hex(0x01D3D1), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_alertPrev, 150, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_alertPrev, 10, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_bg_color(ui_alertPrev, lv_color_hex(0x01D3D1), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_alertPrev, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_border_color(ui_alertPrev, lv_color_hex(0x01D3D1), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_border_opa(ui_alertPrev, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_border_width(ui_alertPrev, 3, LV_PART_MAIN| LV_STATE_PRESSED);

ui_alertNext = lv_img_create(ui_alertPanel);
lv_img_set_src(ui_alertNext, &ui_img_32_next_png);
lv_obj_set_width( ui_alertNext, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_alertNext, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_alertNext, 15 );
lv_obj_set_y( ui_alertNext, 15 );
lv_obj_set_align( ui_alertNext, LV_ALIGN_BOTTOM_RIGHT );
lv_obj_add_flag( ui_alertNext, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_alertNext, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_alertNext, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_alertNext, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_alertNext, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor(ui_alertNext, lv_color_hex(0x01D3D1), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_alertNext, 150, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_alertNext, 10, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_bg_color(ui_alertNext, lv_color_hex(0x01D3D1), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_alertNext, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_border_color(ui_alertNext, lv_color_hex(0x01D3D1), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_border_opa(ui_alertNext, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_border_width(ui_alertNext, 3, LV_PART_MAIN| LV_STATE_PRESSED);

ui_alertClose = lv_img_create(ui_alertPanel);
lv_img_set_src(ui_alertClose, &ui_img_32_close_png);
lv_obj_set_width( ui_alertClose, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_alertClose, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_alertClose, 15 );
lv_obj_set_y( ui_alertClose, -15 );
lv_obj_set_align( ui_alertClose, LV_ALIGN_TOP_RIGHT );
lv_obj_add_flag( ui_alertClose, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_alertClose, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_alertClose, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_alertClose, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_alertClose, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor(ui_alertClose, lv_color_hex(0x01D3D1), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_alertClose, 150, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_alertClose, 10, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_bg_color(ui_alertClose, lv_color_hex(0x01D3D1), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_alertClose, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_border_color(ui_alertClose, lv_color_hex(0x01D3D1), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_border_opa(ui_alertClose, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_border_width(ui_alertClose, 3, LV_PART_MAIN| LV_STATE_PRESSED);

lv_obj_add_event_cb(ui_brightnessSlider, ui_event_brightnessSlider, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_cameraCapture, ui_event_cameraCapture, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_findPhone, ui_event_findPhone, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_musicPrevious, ui_event_musicPrevious, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_musicNext, ui_event_musicNext, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_musicPlay, ui_event_musicPlay, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_alertPrev, ui_event_alertPrev, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_alertNext, ui_event_alertNext, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_alertClose, ui_event_alertClose, LV_EVENT_ALL, NULL);

}

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_jarvisScreen_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_jarvisScreen);
}
