// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.3.4
// Project name: Jarvis

#ifndef _JARVIS_UI_H
#define _JARVIS_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_events.h"
extern lv_obj_t *ui_jarvisScreen;
extern lv_obj_t *ui_dateArc;
extern lv_obj_t *ui_monthLabel;
extern lv_obj_t *ui_dayLabel;
extern lv_obj_t *ui_timeLabel;
extern lv_obj_t *ui_tempArc;
extern lv_obj_t *ui_tempValue;
extern lv_obj_t *ui_tempHigh;
extern lv_obj_t *ui_tempLow;
extern lv_obj_t *ui_weatherIcon;
extern lv_obj_t *ui_cityLabel;
extern lv_obj_t *ui_notificationPanel;
void ui_event_brightnessSlider( lv_event_t * e);
extern lv_obj_t *ui_brightnessSlider;
extern lv_obj_t *ui_brightnessValue;
extern lv_obj_t *ui_brightnessImage;
extern lv_obj_t *ui_weekdayLabel;
extern lv_obj_t *ui_notifLabel;
extern lv_obj_t *ui_connectPanel;
extern lv_obj_t *ui_connectPanel1;
extern lv_obj_t *ui_logPanel;
extern lv_obj_t *ui_logLabel;
extern lv_obj_t *ui_cameraPanel;
extern lv_obj_t *ui_cameraTitle;
void ui_event_cameraCapture( lv_event_t * e);
extern lv_obj_t *ui_cameraCapture;
extern lv_obj_t *ui_cameraText;
extern lv_obj_t *ui_findTimer;
void ui_event_findPhone( lv_event_t * e);
extern lv_obj_t *ui_findPhone;
extern lv_obj_t *ui_musicPanel;
void ui_event_musicPrevious( lv_event_t * e);
extern lv_obj_t *ui_musicPrevious;
void ui_event_musicNext( lv_event_t * e);
extern lv_obj_t *ui_musicNext;
void ui_event_musicPlay( lv_event_t * e);
extern lv_obj_t *ui_musicPlay;
extern lv_obj_t *ui_musicTitle;
extern lv_obj_t *ui_alertPanel;
extern lv_obj_t *ui_alertTitle;
extern lv_obj_t *ui_alertText;
extern lv_obj_t *ui_alertTime;
void ui_event_alertPrev( lv_event_t * e);
extern lv_obj_t *ui_alertPrev;
void ui_event_alertNext( lv_event_t * e);
extern lv_obj_t *ui_alertNext;
void ui_event_alertClose( lv_event_t * e);
extern lv_obj_t *ui_alertClose;
extern lv_obj_t *ui____initial_actions0;


LV_IMG_DECLARE( ui_img_jarvis_bg_png);   // assets\jarvis_bg.png
LV_IMG_DECLARE( ui_img_dy3_png);   // assets\dy3.png
LV_IMG_DECLARE( ui_img_brightness_png);   // assets\brightness.png
LV_IMG_DECLARE( ui_img_diaphragm_png);   // assets\diaphragm.png
LV_IMG_DECLARE( ui_img_32_serach_png);   // assets\32_serach.png
LV_IMG_DECLARE( ui_img_back_32m_png);   // assets\back_32m.png
LV_IMG_DECLARE( ui_img_next_32m_png);   // assets\next_32m.png
LV_IMG_DECLARE( ui_img_32_play_png);   // assets\32_play.png
LV_IMG_DECLARE( ui_img_32_back_png);   // assets\32_back.png
LV_IMG_DECLARE( ui_img_32_next_png);   // assets\32_next.png
LV_IMG_DECLARE( ui_img_32_close_png);   // assets\32_close.png
LV_IMG_DECLARE( ui_img_btn_bg_1_png);   // assets\btn_bg_1.png
LV_IMG_DECLARE( ui_img_btn_bg_2_png);   // assets\btn_bg_2.png
LV_IMG_DECLARE( ui_img_btn_bg_3_png);   // assets\btn_bg_3.png
LV_IMG_DECLARE( ui_img_call1_png);   // assets\call1.png
LV_IMG_DECLARE( ui_img_call2_png);   // assets\call2.png
LV_IMG_DECLARE( ui_img_dy0_png);   // assets\dy0.png
LV_IMG_DECLARE( ui_img_dy1_png);   // assets\dy1.png
LV_IMG_DECLARE( ui_img_dy2_png);   // assets\dy2.png
LV_IMG_DECLARE( ui_img_dy4_png);   // assets\dy4.png
LV_IMG_DECLARE( ui_img_dy5_png);   // assets\dy5.png
LV_IMG_DECLARE( ui_img_dy6_png);   // assets\dy6.png
LV_IMG_DECLARE( ui_img_dy7_png);   // assets\dy7.png
LV_IMG_DECLARE( ui_img_heart2_png);   // assets\heart2.png
LV_IMG_DECLARE( ui_img_nt0_png);   // assets\nt0.png
LV_IMG_DECLARE( ui_img_nt1_png);   // assets\nt1.png
LV_IMG_DECLARE( ui_img_nt2_png);   // assets\nt2.png
LV_IMG_DECLARE( ui_img_nt3_png);   // assets\nt3.png
LV_IMG_DECLARE( ui_img_nt4_png);   // assets\nt4.png
LV_IMG_DECLARE( ui_img_nt5_png);   // assets\nt5.png
LV_IMG_DECLARE( ui_img_nt6_png);   // assets\nt6.png
LV_IMG_DECLARE( ui_img_nt7_png);   // assets\nt7.png


LV_FONT_DECLARE( ui_font_bolld_100);
LV_FONT_DECLARE( ui_font_Font1);
LV_FONT_DECLARE( ui_font_regular100);
LV_FONT_DECLARE( ui_font_regular_120);
LV_FONT_DECLARE( ui_font_semi100);


void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
