// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.3.4
// Project name: Jarvis

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void brightnessChange(lv_event_t * e);
void cameraCapture(lv_event_t * e);
void findPhone(lv_event_t * e);
void musicPrevious(lv_event_t * e);
void musicNext(lv_event_t * e);
void musicToggle(lv_event_t * e);
void alertPrev(lv_event_t * e);
void alertNext(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
